In [1]:
# 166

for num in range(100) :
    print(num)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

In [2]:
# 162

for year in range(2002, 2051, 4):
    print(year)

2002
2006
2010
2014
2018
2022
2026
2030
2034
2038
2042
2046
2050

In [3]:
# 163

for num in range(1, 30 + 1):
    if num % 3 == 0:
        print(num)

3
6
9
12
15
18
21
24
27
30

In [7]:
# 164

for num in range(99, -1, -1):
    print(num)

print(); print('다른 문풀'); print()

for num in range(100):
    print(99-num)

99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0

다른 문풀

99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0

In [11]:
# 165

for num in range(10):
    print(num / 10)

0.0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9

In [13]:
# 166

for num in range(1, 10):
    print(f'3X{num} = {3 * num}')

3X1 = 3
3X2 = 6
3X3 = 9
3X4 = 12
3X5 = 15
3X6 = 18
3X7 = 21
3X8 = 24
3X9 = 27

In [14]:
# 167

for num in range(1, 9 + 1, 2):
        print(f'3X{num} = {3 * num}')

3X1 = 3
3X3 = 9
3X5 = 15
3X7 = 21
3X9 = 27

In [15]:
# 168

total = 0

for num in range(11):
    total += num
    print(total)

0
1
3
6
10
15
21
28
36
45
55

In [18]:
# 169

total = 1

for num in range(1, 11):
    total *= num
    print(total)

1
2
6
24
120
720
5040
40320
362880
3628800